trigger:
  paths:
    include:
      - content/english/**

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: AutoTranslate
  steps:
  - checkout: self
    submodules: true

  - script: |
      changed_folders=$(git diff --name-only HEAD~1 HEAD | grep '^content/english/' | cut -d'/' -f3 | sort | uniq)
      for folder in $changed_folders; do
        ./translation-tool/translate.sh content/english/$folder
      done
    displayName: 'Run Translation Tool'